### ISSUE TITLE
请问地址是怎么解析的？

### ISSUE THREAD

**Issue by lijs11** [fire3/sailorcast#4]
想搞明白地址是怎么解析的，想写个iOS的、另外此APP看了，图标现在看实在太丑了。

**Comment by fire3** [comment]
SailorCast/src/main/java/com/crixmod/sailorcast/siteapi 里面有各个网站的解析代码。没有整理说明文档，从频道解析、剧集解析、真实播放链接获取都有。 主要接口来自对各个视频网站自家安卓app的逆向工程。 APP确实丑了点，本人也不是专职的APP程序员，网上随便找了点图标，水平太业余了，呵呵。。。

另外有个疑问，这个如果写个iOS的，可能不能上架啊，视频应用审核据说很严格啊，毕竟不像安卓这边没人管。

**Comment by lijs11** [comment]
不会安卓，看的好累。
 ios上架确实困难，但是我看到有人引用自己的json描述数据，最后播放的还是youku的地址。

**Comment by yovenny** [comment]
"主要接口来自对各个视频网站自家安卓app的逆向工程" 指的是抓包吗？还是反编译可以看得到接口？
